import js from '@eslint/js'
import globals from 'globals'
import prettier from 'eslint-config-prettier'
import vue from 'eslint-plugin-vue'
import vueParser from 'vue-eslint-parser'
import tseslint from 'typescript-eslint'

import fermata from './tools/eslint/no-windows-path-literals.mjs'

/**
 * One config, four environments.
 *
 * The process split in this repo is a real boundary — main runs in Node with
 * filesystem access, the renderer runs in a sandboxed Chromium with neither —
 * and the globals each half is allowed to see differ accordingly. Getting that
 * wrong in the linter would let `fs` autocomplete in a renderer file that can
 * never load it.
 *
 * Type-aware linting is deliberately off. `npm run typecheck` already runs the
 * real compiler over both tsconfigs, so a second, slower type analysis inside
 * ESLint would duplicate the gate rather than widen it.
 */
export default tseslint.config(
  {
    // Flat config's ignores are the only global ones; every other block's
    // `files` is additive.
    ignores: [
      'out/',
      'dist/',
      'release/',
      'coverage/',
      'node_modules/',
      // Agent scratch space, including git worktrees. Each worktree is a full
      // checkout with its own `tsconfig.json`, and typescript-eslint refuses to
      // guess a project root when it can see several — so one abandoned worktree
      // would otherwise fail the lint gate on every file in the repository.
      '.claude/',
      // Regenerated by the unplugin auto-import/components scan on each dev run.
      'src/renderer/auto-imports.d.ts',
      'src/renderer/components.d.ts'
    ]
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...vue.configs['flat/recommended'],

  {
    name: 'fermata/base',
    plugins: { fermata },
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module'
    },
    rules: {
      // `_`-prefixed parameters are the documented way to say "required by the
      // signature, unused by this implementation" — same convention tsconfig's
      // noUnusedParameters uses.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }
      ],
      // Interfaces with no members are how `src/shared` marks a payload that is
      // intentionally empty for now.
      '@typescript-eslint/no-empty-object-type': 'off',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      // `info` is the level this project uses for deliberate diagnostics that
      // are part of a feature — the schema-migration line, R1's decode-cost
      // telemetry. Barring `log` is what keeps a debugging session from
      // shipping; `lint` runs with --max-warnings=0, so this is a gate.
      'no-console': ['error', { allow: ['warn', 'error', 'info'] }]
    }
  },

  {
    name: 'fermata/main-and-preload',
    files: ['src/main/**/*.ts', 'src/preload/**/*.ts'],
    languageOptions: {
      globals: globals.node
    }
  },

  {
    name: 'fermata/renderer',
    files: ['src/renderer/**/*.{ts,vue}'],
    languageOptions: {
      globals: globals.browser,
      parser: vueParser,
      parserOptions: {
        // vue-eslint-parser owns the SFC; the TS parser handles what is inside
        // <script setup lang="ts">.
        parser: tseslint.parser,
        extraFileExtensions: ['.vue'],
        sourceType: 'module'
      }
    },
    rules: {
      // Nuxt UI and the auto-import plugin both register multi-word components
      // this rule cannot see, and panel filenames are the project's convention.
      'vue/multi-word-component-names': 'off',
      // The renderer has no filesystem and no Node builtins by design; a Node
      // global appearing here means the context isolation boundary was crossed.
      'no-restricted-globals': [
        'error',
        { name: 'require', message: 'The renderer has no Node runtime. Cross IPC instead.' },
        { name: 'process', message: 'The renderer has no Node runtime. Cross IPC instead.' },
        { name: '__dirname', message: 'The renderer has no Node runtime. Cross IPC instead.' }
      ]
    }
  },

  {
    name: 'fermata/shared',
    files: ['src/shared/**/*.ts'],
    languageOptions: {
      // No globals at all. src/shared is imported by main, preload and the
      // renderer alike, so anything it reaches for has to exist in all three.
      globals: {}
    }
  },

  {
    // The invariant this enforces is about what ships, not about how tests
    // describe it: `tests/main/db/paths.test.ts` is a wall of literal Windows
    // paths, and that is exactly its job.
    name: 'fermata/path-portability',
    files: ['src/**/*.{ts,vue}'],
    rules: {
      'fermata/no-windows-path-literals': 'error'
    }
  },

  {
    name: 'fermata/tests',
    files: ['tests/**/*.ts'],
    languageOptions: {
      globals: globals.node
    },
    rules: {
      // Tests reach into private shapes and stub half-built objects; demanding
      // a full type for a fixture is how `as any` ends up in shipped code.
      '@typescript-eslint/no-explicit-any': 'off'
    }
  },

  {
    name: 'fermata/tooling',
    files: ['*.config.{ts,js,mjs}', 'scripts/**/*.mjs', 'tools/**/*.mjs'],
    languageOptions: {
      globals: globals.node
    },
    rules: {
      // These are the scripts whose whole purpose is talking to the terminal.
      'no-console': 'off'
    }
  },

  // Last: turns off every stylistic rule Prettier already decides.
  prettier
)
